version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # Bundle all NuGet updates into a single pull request instead of
    # opening a separate PR per package.
    groups:
      nuget-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      docker-images:
        patterns:
          - "*"
